### ISSUE TITLE
Gallery Post Format: Standardise size

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-corp#10]
@adiraomj For this primary grid layout, can we look at a method of standardising the image size for the archive view. Can we use `siteorigin_corp_get_gallery` to do this based on the view, archive or single?

**Comment by adiraomj** [comment]
By default the `get_post_gallery` function returns the image urls for the image size that the user has defined while creating the gallery. 

I have worked on a hack. What image sizes should we set for archive and single galleries?

**Comment by Misplon** [comment]
Thanks @adiraomj. In the case of the grid layout, the gallery needs to match the other featured image sizes in the grid. On single it can be display at user selected size.

**Comment by Misplon** [comment]
@adiraomj Quick follow-up here when possible. Thanks :)

**Comment by Misplon** [comment]
Let's leave it with the default behaviour.

_By default the `get_post_gallery function` returns the image urls for the image size that the user has defined while creating the gallery._
