### ISSUE TITLE
Flexslider Galleries: Images visible on load

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-corp#11]
All slider images are visible on load and then hide. The same issue persists in Unwind.

**Comment by adiraomj** [comment]
I'm unable to replicate the issue. Do you see this in archive or single pages?

**Comment by Misplon** [comment]
You can see it on both archive and single.

Quick video: https://www.dropbox.com/s/9dfue4kfh2lbkjz/gallery.mp4?dl=0

**Comment by Misplon** [comment]
@adiraomj Please, check the commit above for me. Works on my side. Thanks :)

**Comment by adiraomj** [comment]
@Misplon looks good. Maybe fix the indentation [here](https://github.com/siteorigin/siteorigin-corp/commit/bda91b05a446c6848ad980d175ada6943c1c8989?diff=split#diff-3b3e269aec31d42292b05e8e884edaa3R72)
