### ISSUE TITLE
WooCommerce: Add error checking to Quick View

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-corp#115]
Investigate adding error checking to the Quick View. Currently, if the product has options and you don't select options, error checking is done on the product page.

**Comment by AlexGStapleton** [comment]
This currently doesn't happen as WooCommerce isn't connected to the Quick View. Connecting it will result in the variation working how it does on the product page. Do you want to hide the variation description?

**Comment by AlexGStapleton** [comment]
Resolved by https://github.com/siteorigin/siteorigin-corp/issues/115
