### ISSUE TITLE
Quick View: Only display the Clear link when an option has been selected

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-corp#116]
![Products_–_SiteOrigin](https://user-images.githubusercontent.com/789159/79376468-8302bb80-7f5a-11ea-8e6a-7167aa329835.png)

Mimic the behavior of normal product pages by only displaying the clear link once an option has been selected.

**Comment by AlexGStapleton** [comment]
Resolved by https://github.com/siteorigin/siteorigin-corp/issues/115
