### ISSUE TITLE
Quick View: Prevent a hash from being added to the URL when clear link is clicked

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-corp#117]
Prevent a hash from being added to the URL when the quick view clear link is clicked.

![hash](https://user-images.githubusercontent.com/789159/79376755-ebea3380-7f5a-11ea-8f2f-92199377d8d2.png)

**Comment by AlexGStapleton** [comment]
Resolved by https://github.com/siteorigin/siteorigin-corp/issues/115
