### ISSUE TITLE
Single Post: Next and Previous aren't available for translation

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-corp#129]
https://github.com/siteorigin/siteorigin-corp/blob/develop/inc/template-tags.php#L247

The Next and Previous strings aren't making it into the theme .pot file and therefore can't be translated at the moment.

**Comment by AlexGStapleton** [comment]
I created a build and these strings were in the generated .pot file. Can you please try reinstalling the build script to see if that helps? [Here's the generated .pot file](https://drive.google.com/uc?id=1lrmox7P1zwmO_AjKtCDZaiRFMVZhvNOH).

**Comment by Misplon** [comment]
I've resolved the issue by running `npm install`.
