### ISSUE TITLE
WC Quickview: Variation Swatches plugin no longer selectable

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-corp#133]
https://wordpress.org/plugins/woo-variation-swatches/ is quite a popular plugin. Up until recently, it worked normally with quick view, this is no longer the case.

**Comment by AlexGStapleton** [comment]
That plugin appears to be working without issue for me while using development. Are you testing using the release or master version? I ask as those versions won't have https://github.com/siteorigin/siteorigin-corp/pull/130

Please note that Corp Quick View didn't work prior to that PR. Compatability was added to [the Unwind Quick View](https://github.com/siteorigin/siteorigin-unwind/issues/282), and not Corp.
