### ISSUE TITLE
SiteOrigin Corp and Classic Editor - post meta being inherited from other posts

### ISSUE THREAD

**Issue by mstaudinger** [siteorigin/siteorigin-corp#156]
I've got a weird one - here's the quick summary: when both Classic Editor plugin is active, and SiteOrigin Corp is the active theme, I have observed strange behavior when adding and editing pages.

EDIT - will close this one out. There's nothing like explaining the problem to track it down.  This was actually some local code at fault, which was copied to the development site in error.  It escaped my notice since it wasn't me doing the editing.

**Comment by mstaudinger** [comment]
User error :)

**Comment by Misplon** [comment]
Hi Mark

Thanks for keeping this issue updated. I'm glad to hear you've made progress and found the cause of the problem.

If any SiteOrigin related queries or requests arise in the future, please, let us know.

Cheers for now.

Andrew
