### ISSUE TITLE
Google Fonts aren't importing outside of customizer preview

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-corp#19]
In the latest release version of Corp, Google Fonts aren't being imported on the actual website itself but are being imported in the customizer.

Reference images.

Customizer settings:
![](https://i.imgur.com/JLqpxOE.png)

Frontend results:
![](https://i.imgur.com/rCw3wAD.gif)

**Comment by Misplon** [comment]
Will try resolve ASAP.

**Comment by Misplon** [comment]
Adi and Greg can't replicate. 
I can replicate with `develop` but when I try the .org repo version, I can't replicate.
