### ISSUE TITLE
[bug] jquery.woocommerce.min.js - Missing in 1.3.3

### ISSUE THREAD

**Issue by SmashBrando** [siteorigin/siteorigin-corp#24]
It appears the folder for jquery.woocommerce.min.js is empty in this release (I see it's in the repo but a fresh install has an empty woocommerce/js/ folder).

In addition to this file not being found, it's located both in the main js folder and the woocommerce/js folder within the git repo. Possibly some cleanup todo here.

**Comment by Misplon** [comment]
Hi @SmashBrando 

Will resolve ASAP. Sorry for the hassle. Appreciate the heads up. At a glance it looks like an issue with the build config. Working it now.

**Comment by Misplon** [comment]
https://github.com/siteorigin/siteorigin-corp/commit/7b0d0063ac182c6e64b0cc1188aa873ce4af4d13

**Comment by SmashBrando** [comment]
@Misplon no hassle at all. Thanks for the quick fix :)
