### ISSUE TITLE
Implement Breadcrumbs: Add action, check styling, add to docs

### ISSUE THREAD

**Issue by SmashBrando** [siteorigin/siteorigin-corp#25]
One of the features mentioned are breadcrumbs. I see the template tag markup but not the actual output anywhere in the template files.

I assume this still needs to be integrated and styled or needs to be removed as a feature.

**Comment by Misplon** [comment]
You're quite right, hasn't been implemented yet. You can get it going right now if you add this function to your child theme:

```
if ( ! function_exists( 'siteorigin_corp_breadcrumbs' ) ) :
/**
 * Display's breadcrumbs supported by Yoast SEO & Breadcrumb NavXT.
 */
function siteorigin_corp_breadcrumbs() {
	if ( function_exists( 'bcn_display' ) ) {
		?><div class="breadcrumbs bcn">
			<?php bcn_display(); ?>
		</div><?php
	} elseif( function_exists( 'yoast_breadcrumb' ) ) {
		yoast_breadcrumb( '<div class="breadcrumbs">','</div>' );
	}
}
endif;
add_action( 'siteorigin_corp_content_top', 'siteorigin_corp_breadcrumbs' );
```

I'll have it included in the next release. The action had been removed. Thanks for the reminder!

**Comment by Misplon** [comment]
Resolved via: https://github.com/siteorigin/siteorigin-corp/commit/f8cc93c191a2953a8263948303a984e27051d307
