### ISSUE TITLE
Transparent site header & smart slider 3 (pro) - only on firefox

### ISSUE THREAD

**Issue by DESIGNMENOW** [siteorigin/siteorigin-corp#28]
Hello Siteorigin team,

great job first of all. Love your well-structured & clear themes.
Maybe I found a little bug with your theme in Firefox, 59.0.2 (64-Bit, Windows). 
Chrome and Edge work fine.
It occurs on pages with
- siteorigin-corp (Siteorigin Page Builder Premium) 
- Smart Slider 3 (Pro) when
- transparent header is enabled

When scrolling down, there is no class '.stuck' added to  '.site-header'. Thus the header stays transparent on page scroll.
This only happens on pages with smart slider 3 in Firefox.
Pages without slider and transparent header work fine. Background of header becomes white on page scroll.
I had also tried to add the class via JS myself. But that does not change anything. The class '.stuck' won't be added.

Therefore I do not know if it concers your theme or the slider. I had all extras disabled on the slider side (extra loading of jquery etc.) No effects.
Any ideas or workarounds?
Have a nice day
Tobi

**Comment by Misplon** [comment]
Hi Tobi

Thanks for reaching out. I can't yet replicate. Are there any errors in the [Console](https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors#Step_3:_Diagnosis)?

**Comment by Misplon** [comment]
Can you perhaps see if this issue persists using only the free version of Smart Slider 3? Thanks.

**Comment by Misplon** [comment]
Thanks for the detailed feedback. I can't replicate the issue at the moment using Full-Width:

![full-width](https://user-images.githubusercontent.com/789159/39006007-043abd24-4402-11e8-8e2b-6a83e61a3ee8.png)
![overlap-light](https://user-images.githubusercontent.com/789159/39006008-0493e5f2-4402-11e8-91b6-e38fd043aa5c.png)
![overlap-scroll](https://user-images.githubusercontent.com/789159/39006014-0574469c-4402-11e8-97c5-2ab7b97ca856.png)

I've asked nextendweb.com for a copy of Smart Slider 3 Pro. I'll try testing with it as soon as I get a copy.

**Comment by Misplon** [comment]
I've tried with Pro now, still not able to replicate.

Can you perhaps test with all non-SiteOrigin plugins disabled (except Smart Slider) and see if it persists?

If the issue persists, can you perhaps send me an export of your slider? https://smartslider3.helpscoutdocs.com/article/370-import-slider

(If you're using SiteOrigin Premium, please keep in mind that you can use email support at anytime. support@siteorigin.com).

**Comment by DESIGNMENOW** [comment]
Hey, 

sorry for my delayed reply.
Sure, I will give it a try with all other plugins disabled. 
Another side note: using WP multi site installation.
Will come back to this thread during the weekend.

Thanks for the reminder. Thought it could also help other users when publishing it on git.

**Comment by Misplon** [comment]
Hi, are you still working through this issue? If so, can you perhaps setup a demo page so we can take a look? Thanks :)
