### ISSUE TITLE
A few color settings aren't working after upadte

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-corp#31]
The Link Hover Color setting and Drop Down menu settings don't currently appear to work. This looks to be due to a selector change in the stylesheets, but not in the Customizer styling.

![](https://i.imgur.com/VWp1SIH.png)
![](https://i.imgur.com/TwFMv4t.png)
![](https://i.imgur.com/WLZak6j.png)

**Comment by Misplon** [comment]
@AlexGStapleton Please, pull `develop` and test. Once happy I can push a hotfix release.

**Comment by Misplon** [comment]
Resolved https://github.com/siteorigin/siteorigin-corp/commit/693cfa40ae49aeea2bb3461c6c8440e53e86caa2.
