### ISSUE TITLE
Post Meta: Add an option to add post author

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-corp#40]
Add an option to add the post author.

**Comment by Misplon** [comment]
@AlexGStapleton https://github.com/siteorigin/siteorigin-corp/commit/ec03f8cf20bb1fca0e5984d084b15f6088e50471

Keen for any changes there mate?

**Comment by AlexGStapleton** [comment]
👍

**Comment by Misplon** [comment]
Sweet, thanks for checking.
