### ISSUE TITLE
Change Post Loop templates post titles to h3

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-corp#46]
Currently, the post loop titles are set to h2. This is pretty high due to where the titles will be on the page so we should reduce it to h3.

**Comment by Misplon** [comment]
@AlexGStapleton Are we sure about this? On your blog page your site title will be `p`, perhaps you add a page title which is `h1`, is it not logical for the post titles to be `h2`?

**Comment by AlexGStapleton** [comment]
Ah. I wasn't aware of that. In that case, the only potential issue I see is when a user adds a post loop widget pretty low on the page but there's no real way of avoiding that without altering the header for all uses.

**Comment by Misplon** [comment]
Ok cool, let's leave this for a bit. It's really easy to child theme if users need the tag changed. Styling targets the class name so no CSS changes should be required. If it comes up a few more times we can dive back in.
