### ISSUE TITLE
Cart icon auto height is causing display issues in IE 11

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-corp#49]
Here's what the Corp header looks like in IE 11:

![](https://vgy.me/4tWrVG.png)

Here's what it looks like when [this line](https://github.com/siteorigin/siteorigin-corp/blob/1.9/sass/woocommerce/_cart.scss#L103) is removed.

![](https://vgy.me/ay84oR.png)

The alignment is fixed but the cart icon is smaller. The likely fix to this issue looks to be remove `height: auto;` and apply a static height but I'm not too sure if I'm overlooking something.

**Comment by Misplon** [comment]
Good old MS.

**Comment by Misplon** [comment]
@AlexGStapleton Please, can you test the change. Thanks.

**Comment by AlexGStapleton** [comment]
Looks good! 👍
