### ISSUE TITLE
Certain theme settings aren't updating correctly

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-corp#64]
A user has reported that settings in the following settings aren't updating correctly as of the last update: header, Typography, and footer.

I've run a few tests and have been able to confirm that none of the settings  (such as the Fonts)  I tried worked. They saved but they didn't output in the customizer preview or on the website directly. The settings were reflected correctly in the relevant settings panel though so that suggests a change to how the CSS is generated has caused this issue.

The following error is present after opening the customizer:

```
Uncaught TypeError: Cannot read property 'replace' of null
    at replaceAll (live.js?ver=1.9.6:12)
    at updateCss (live.js?ver=1.9.6:35)
    at HTMLDocument.<anonymous> (live.js?ver=1.9.6:147)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
```

**Comment by AlexGStapleton** [comment]
This issue only occurs when certain settings are enabled/disabled. I was able to replicate this issue when I disabled the **Mobile Menu** on a fresh install. This likely isn't the only setting causing this issue.

**Comment by Misplon** [comment]
Confirmed. When deactivating the Mobile Menu I see the above issues.

**Comment by Misplon** [comment]
Might be resolved via https://github.com/siteorigin/siteorigin-corp/commit/ca287da75c004678bb2871afbfe7bb7849a2dc55. Let me know.

**Comment by Misplon** [comment]
Resolved via https://github.com/siteorigin/siteorigin-corp/commit/ca287da75c004678bb2871afbfe7bb7849a2dc55.
