### ISSUE TITLE
Sub Menu Top Border isn't aligned with the other menu item borders

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-corp#73]
This issue can be seen in the Corp demo:
<img width="181" alt="2019-06-07_02-39-02-721" src="https://user-images.githubusercontent.com/17275120/59050420-a1754080-88cd-11e9-8e5d-8921c945b985.png">

I was able to fix this on a premium users site by increasing [the sub menu top](https://github.com/siteorigin/siteorigin-corp/blob/1.11.2/sass/navigation/_menus.scss#L23) to 21px, but that isn't working on the demo.

**Comment by Misplon** [comment]
@AlexGStapleton Is this still happening or did I perhaps fix and forget to resolve this? I can't replicate at the moment.

<img width="1002" alt="Home_-_Corp" src="https://user-images.githubusercontent.com/789159/62835096-ac917780-bc54-11e9-9ad7-8a93a0eefc24.png">

**Comment by AlexGStapleton** [comment]
Looks like this was fixed at some point.

**Comment by Misplon** [comment]
Super, thanks for confirming.
