### ISSUE TITLE
Page Settings on Custom Post Types

### ISSUE THREAD

**Issue by SmashBrando** [siteorigin/siteorigin-corp#82]
I'm working on a child theme that includes a couple custom post types and am trying to determine the slug to use to declare support for Page Settings on the post type and haven't been able to uncover anything searching the codebase.

Is this possible?

**Comment by Misplon** [comment]
Hi @SmashBrando 

Thanks for posting. Are you asking how to declare support or how to locate the post type slug? Here is how you'd declare support:

```
function add_page_settings_support_custom() {
	add_post_type_support( 'custom_post_type', 'so-page-settings' );
}
add_action( 'init', 'add_page_settings_support_custom' );
```

**Comment by SmashBrando** [comment]
Thanks @Misplon that was exactly what I was looking for :)

**Comment by Misplon** [comment]
Super :) Glad that helped.
