### ISSUE TITLE
One Page Navigation: Refactor to handle first scroll of scaling header

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-corp#94]
Our [headerHeight](https://github.com/siteorigin/siteorigin-corp/blob/develop/js/jquery.theme.js#L84-L99) function isn't able to calculate the height of the scaled header in the first scroll. The result is that we land short of the anchor.

<img width="1414" alt="One_Page_Demo_-_Corp" src="https://user-images.githubusercontent.com/789159/66223291-6811dd80-e6d3-11e9-876e-db75d9659acb.png">

The issue can be seen in the [demo](https://demo.siteorigin.com/corp/one-page-demo/).

**Overview**
The one-page smooth scrolling and menu page section indication functionality is broken up into the following parts:

**Main menu section indication:**
https://github.com/siteorigin/siteorigin-corp/blob/develop/js/jquery.theme.js#L69-L81
https://github.com/siteorigin/siteorigin-corp/blob/develop/js/jquery.theme.js#L162-L203

**Smooth scrolling from internal page anchors:**
https://github.com/siteorigin/siteorigin-corp/blob/develop/js/jquery.theme.js#L83-L146

**Header offset from external page anchors:**
https://github.com/siteorigin/siteorigin-corp/blob/develop/js/jquery.theme.js#L148-L160

**Comment by AlexGStapleton** [comment]
I'm having trouble replicating this locally, and on the demo site. I tried both Chrome and Firefox. Are you still able to replicate this?

**Comment by Misplon** [comment]
Yeah, it's there on the demo.

![first-click](https://user-images.githubusercontent.com/789159/91839679-c16dee00-ec4f-11ea-8a30-3031716f1d8e.jpg)

![02](https://user-images.githubusercontent.com/789159/91839684-c337b180-ec4f-11ea-9d7a-656d70acba29.jpg)

**Comment by AlexGStapleton** [comment]
I was able to replicate this locally. This issue is tied to the Logo Scaling.

**Comment by Misplon** [comment]
Yeah, that's it.
